source 'https://rubygems.org'
ruby '2.2.2'
gem 'rails'
gem 'pg'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks', :git => 'https://github.com/rails/turbolinks.git'
gem 'jbuilder'
gem 'dotenv-rails'
gem 'dalli'
gem 'thin'
gem 'devise'
gem 'materialize-sass', :git => 'https://github.com/mkhairi/materialize-sass.git'
gem 'toastr-rails'
gem 'pry'
gem 'sdoc', group: :doc
group :development, :test do
  gem 'byebug'
  gem 'rspec'
  gem 'web-console'
  gem 'spring'
end
